# Generated by Django 3.2 on 2022-04-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantiti',
            field=models.PositiveIntegerField(default=0, verbose_name='количество'),
        ),
    ]
