# Generated by Django 3.2 on 2022-04-16 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_product_quantiti'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantiti',
            new_name='quantity',
        ),
    ]
